name: shellharden
base: core18 # the base snap is the execution environment for this snap
adopt-info: shellharden
summary: The corrective bash syntax highlighter
description: |
  Shellharden is a syntax highlighter and a tool to semi-automate
  the rewriting of scripts to ShellCheck conformance, mainly focused
  on quoting.
  The default mode of operation is like cat, but with syntax highlighting
  in foreground colors and suggestive changes in background colors.

grade: stable
confinement: strict

parts:
  shellharden:
    plugin: rust
    rust-channel: stable
    source: .
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(git describe --tags)

apps:
  shellharden:
    command: bin/shellharden
    plugs:
      - home
      - removable-media